import { beforeEach, describe, expect, it } from 'vitest';
import {
  listWorkflowPRDHistoryIds,
  saveWorkflowPRDVersion,
} from '../prdStorage';

const PROJECT = 'history-project';

beforeEach(() => {
  localStorage.clear();
});

describe('workflow history discovery', () => {
  it('keeps history addressable even when a workflow no longer has a current PRD', () => {
    saveWorkflowPRDVersion(
      PROJECT,
      'removed-workflow',
      {
        workflowId: 'removed-workflow',
        workflowName: 'Removed workflow',
        version: 1,
        sections: [],
        manualEditedAt: {},
        autoGenerated: true,
      } as any,
      'ai-generate',
    );

    expect(listWorkflowPRDHistoryIds(PROJECT)).toEqual(['removed-workflow']);
  });
});