import type { AiClient, AiMessage } from './types';
import type { AiRouter } from './router';
import type { SemanticWorkflowModel } from '../lib/kiteframe/utils/extractSemanticWorkflowModel';
import { normalizeGeneratedPrdSection } from './prdMarkdown';

export interface PRDSection {
  id: string;
  title: string;
  content: string;
}

export interface WorkflowPRD {
  workflowId: string;
  workflowName: string;
  sections: PRDSection[];
  manualEditedAt: Record<string, number>;
  version: number;
  generatedAt: number;
  hash?: string;
  sectionHashes?: Record<string, string>;
  autoGenerated?: boolean;
  draft?: boolean;
  /**
   * ISO timestamp of the last server-side save. Stamped by the documents API
   * (see `shared/documents.ts`), so it is absent on documents generated before
   * server persistence existed — resolve it via `resolveDocumentUpdatedAt`
   * rather than reading it directly.
   */
  updatedAt?: string;
}

export interface ProjectPRD {
  projectId: string;
  projectName: string;
  sections: PRDSection[];
  manualEditedAt: Record<string, number>;
  version: number;
  generatedAt: number;
  autoGenerated?: boolean;
  /** ISO timestamp of the last server-side save. See `WorkflowPRD.updatedAt`. */
  updatedAt?: string;
}

type AiClientOrRouter = AiClient | AiRouter;

export type PRDGenerationStatus = 'waiting-for-capacity' | 'running';

function isRouter(client: AiClientOrRouter): client is AiRouter {
  return 'chat' in client && !('stream' in client);
}

const PRD_SECTION_CONCURRENCY = 2;
const PRD_CAPACITY_RETRY_LIMIT = 3;
const PRD_CAPACITY_RETRY_BASE_DELAY_MS = 250;

type PrdWorkItem = {
  run: () => Promise<unknown>;
  resolve: (value: unknown) => void;
  reject: (reason: unknown) => void;
  signal?: AbortSignal;
  abortHandler?: () => void;
  state: 'queued' | 'running' | 'settled';
};

const prdWorkQueue: PrdWorkItem[] = [];
let activePrdWorkCount = 0;

function createAbortError(): DOMException {
  return new DOMException('Aborted', 'AbortError');
}

function isAbortError(error: unknown): boolean {
  return error instanceof Error && error.name === 'AbortError';
}

function throwIfAborted(signal?: AbortSignal): void {
  if (signal?.aborted) {
    throw createAbortError();
  }
}

function removeQueuedWork(item: PrdWorkItem): void {
  const index = prdWorkQueue.indexOf(item);
  if (index !== -1) {
    prdWorkQueue.splice(index, 1);
  }
}

function releaseAbortHandler(item: PrdWorkItem): void {
  if (item.signal && item.abortHandler) {
    item.signal.removeEventListener('abort', item.abortHandler);
  }
  item.abortHandler = undefined;
}

function drainPrdWorkQueue(): void {
  while (activePrdWorkCount < PRD_SECTION_CONCURRENCY && prdWorkQueue.length > 0) {
    const item = prdWorkQueue.shift()!;

    if (item.state !== 'queued') {
      continue;
    }

    if (item.signal?.aborted) {
      item.state = 'settled';
      releaseAbortHandler(item);
      item.reject(createAbortError());
      continue;
    }

    item.state = 'running';
    releaseAbortHandler(item);
    activePrdWorkCount += 1;

    void Promise.resolve()
      .then(item.run)
      .then(item.resolve, item.reject)
      .finally(() => {
        item.state = 'settled';
        activePrdWorkCount -= 1;
        drainPrdWorkQueue();
      });
  }
}

/**
 * All project and workflow PRD sections share this queue. Leaving one service
 * slot free avoids colliding with a user's separate KiteAI request while still
 * generating sections in parallel.
 */
function queuePrdWork<T>(run: () => Promise<T>, signal?: AbortSignal): Promise<T> {
  if (signal?.aborted) {
    return Promise.reject(createAbortError());
  }

  return new Promise<T>((resolve, reject) => {
    const item: PrdWorkItem = {
      run,
      resolve: (value) => resolve(value as T),
      reject,
      signal,
      state: 'queued',
    };

    if (signal) {
      item.abortHandler = () => {
        if (item.state !== 'queued') return;
        item.state = 'settled';
        removeQueuedWork(item);
        releaseAbortHandler(item);
        reject(createAbortError());
      };
      signal.addEventListener('abort', item.abortHandler, { once: true });
    }

    prdWorkQueue.push(item);
    drainPrdWorkQueue();
  });
}

function isCapacityError(error: unknown): boolean {
  if (!(error instanceof Error)) return false;
  return /AI error:\s*429|too many (concurrent )?AI (operations|requests)/i.test(error.message);
}

function waitForRetry(delayMs: number, signal?: AbortSignal): Promise<void> {
  return new Promise((resolve, reject) => {
    if (signal?.aborted) {
      reject(createAbortError());
      return;
    }

    const timeout = setTimeout(() => {
      signal?.removeEventListener('abort', onAbort);
      resolve();
    }, delayMs);
    const onAbort = () => {
      clearTimeout(timeout);
      reject(createAbortError());
    };
    signal?.addEventListener('abort', onAbort, { once: true });
  });
}

async function callAi(
  client: AiClientOrRouter,
  messages: AiMessage[],
  options: { temperature?: number; maxTokens?: number; signal?: AbortSignal }
): Promise<string> {
  if (isRouter(client)) {
    const response = await client.chat({
      taskType: 'prd_generation',
      messages,
      temperature: options.temperature,
      maxTokens: options.maxTokens,
      signal: options.signal,
    });
    return response.text;
  }
  const response = await client.chat({
    messages,
    temperature: options.temperature,
    maxTokens: options.maxTokens,
    signal: options.signal,
  });
  return response.text;
}

async function generateSectionWithRetry(
  client: AiClientOrRouter,
  context: string,
  sectionTitle: string,
  hint: string,
  signal?: AbortSignal,
  onStatusChange?: (status: PRDGenerationStatus) => void
): Promise<string> {
  let retryCount = 0;

  while (true) {
    throwIfAborted(signal);
    try {
      const content = await generateSectionText(client, context, sectionTitle, hint, signal);
      if (!content) {
        throw new Error(`PRD section "${sectionTitle}" returned no content`);
      }
      return content;
    } catch (error) {
      if (signal?.aborted || isAbortError(error)) {
        throw createAbortError();
      }

      if (!isCapacityError(error) || retryCount >= PRD_CAPACITY_RETRY_LIMIT) {
        throw error;
      }

      const delayMs = PRD_CAPACITY_RETRY_BASE_DELAY_MS * (2 ** retryCount);
      retryCount += 1;
      console.warn(
        `[PRD][SECTION] ${sectionTitle} was delayed by AI capacity; retrying in ${delayMs}ms (${retryCount}/${PRD_CAPACITY_RETRY_LIMIT})`
      );
      onStatusChange?.('waiting-for-capacity');
      try {
        await waitForRetry(delayMs, signal);
      } finally {
        onStatusChange?.('running');
      }
    }
  }
}

const DEFAULT_WORKFLOW_SECTIONS = [
  { id: 'overview', title: 'Overview' },
  { id: 'requirements', title: 'Requirements' },
  { id: 'user-flow', title: 'User Flow' },
  { id: 'inputs-outputs', title: 'Inputs & Outputs' },
  { id: 'failure-scenarios', title: 'Failure Scenarios' },
  { id: 'recovery-fallback', title: 'Recovery & Fallback Paths' },
  { id: 'operational-risks', title: 'Operational Risks' },
  { id: 'acceptance-criteria', title: 'Acceptance Criteria' },
];

const DEFAULT_PROJECT_SECTIONS = [
  { id: 'overview', title: 'Project Overview' },
  { id: 'goals', title: 'Goals & Objectives' },
  { id: 'architecture', title: 'System Architecture' },
  { id: 'workflows', title: 'Workflow Summary' },
  { id: 'assumptions', title: 'Assumptions' },
];

const WORKFLOW_SECTION_HINTS: Record<string, string> = {
  'overview': 'Cover: purpose of this workflow, who uses it, and what problem it solves. Use 3-5 bullet points.',
  'requirements': 'List the top functional and non-functional requirements. Max 5-6 bullet points.',
  'user-flow': 'Describe the step-by-step path from entry to exit. Use numbered steps. Include branching paths.',
  'inputs-outputs': 'List the key data inputs required and outputs produced. Use bullets or a short table.',
  'failure-scenarios': 'Identify the top 3-5 ways this workflow can fail: user errors, system errors, timeouts, edge cases.',
  'recovery-fallback': 'For each failure mode, describe the recovery or fallback path. Use bullet points.',
  'operational-risks': 'List 3-5 operational concerns: monitoring needs, SLA requirements, performance risks, dependencies.',
  'acceptance-criteria': 'Write 4-6 specific, testable acceptance criteria. Use checkboxes or Given/When/Then format.',
};

const PROJECT_SECTION_HINTS: Record<string, string> = {
  'overview': 'Summarize the project: what it does, who it serves, and what it delivers. 3-5 bullet points.',
  'goals': 'List the primary goals and measurable success metrics. Max 5 bullet points.',
  'architecture': 'Describe the system architecture and how the workflows connect. Keep it high-level.',
  'workflows': 'Briefly describe each workflow and its role in the overall system. One bullet per workflow.',
  'assumptions': 'List the key assumptions and constraints this project is built on. Max 5 bullet points.',
};

const SECTION_SYSTEM_PROMPT = 'You are a concise technical writer producing a single PRD section. The surrounding UI already renders the section title, so begin directly with the content. Use headings only for distinct internal subtopics; never repeat the section title as a heading. Use bullet points and plain markdown. Aim for 80-150 words. Do not wrap your entire response in code fences.';

function buildWorkflowContext(model: SemanticWorkflowModel): string {
  const nodesDesc = model.nodes.map(n =>
    `- ${n.label || n.type} (${n.type})${n.description ? `: ${n.description}` : ''}`
  ).join('\n');

  const edgesDesc = model.edges.map(e => {
    const sourceNode = model.nodes.find(n => n.id === e.source);
    const targetNode = model.nodes.find(n => n.id === e.target);
    return `- ${sourceNode?.label || 'Node'} → ${targetNode?.label || 'Node'}${e.label ? ` (${e.label})` : ''}`;
  }).join('\n');

  return `Workflow: ${model.name}
Nodes (${model.nodeCount}):
${nodesDesc}

Connections:
${edgesDesc}

Entry: ${model.entryPoints.join(', ') || 'None identified'}
Exit: ${model.exitPoints.join(', ') || 'None identified'}
Primary Actions: ${model.primaryActions.join(', ') || 'None identified'}
Error Paths: ${model.errorPaths.join(', ') || 'None identified'}`;
}

function buildProjectContext(projectName: string, workflowModels: SemanticWorkflowModel[]): string {
  const workflowSummaries = workflowModels.map(w =>
    `- ${w.name}: ${w.nodeCount} nodes, ${w.edges.length} connections. Entry: ${w.entryPoints[0] || 'N/A'}, Exit: ${w.exitPoints[0] || 'N/A'}`
  ).join('\n');

  return `Project: ${projectName}
Total Workflows: ${workflowModels.length}

Workflows:
${workflowSummaries}`;
}

async function generateSectionText(
  client: AiClientOrRouter,
  context: string,
  sectionTitle: string,
  hint: string,
  signal?: AbortSignal
): Promise<string> {
  const messages: AiMessage[] = [
    { role: 'system', content: SECTION_SYSTEM_PROMPT },
    { role: 'user', content: `${context}\n\nWrite the "${sectionTitle}" section for this PRD.\n${hint}` },
  ];

  const text = await callAi(client, messages, { temperature: 0.3, maxTokens: 500, signal });
  return normalizeGeneratedPrdSection(text, sectionTitle);
}

type PrdSectionDefinition = {
  id: string;
  title: string;
};

type ExistingPrd = {
  sections: PRDSection[];
  manualEditedAt: Record<string, number>;
};

/**
 * Generates a document as an all-or-nothing batch. If a section cannot be
 * generated, abort the rest of the batch instead of returning a document with
 * silent empty gaps that a caller could save as successful.
 */
async function generatePrdSections(
  client: AiClientOrRouter,
  context: string,
  definitions: readonly PrdSectionDefinition[],
  hints: Record<string, string>,
  existingPrd: ExistingPrd | undefined,
  parentSignal?: AbortSignal,
  onStatusChange?: (status: PRDGenerationStatus) => void
): Promise<PRDSection[]> {
  const batchController = new AbortController();
  const abortBatch = () => batchController.abort();
  let waitingSectionCount = 0;
  const updateStatus = (status: PRDGenerationStatus) => {
    if (status === 'waiting-for-capacity') {
      waitingSectionCount += 1;
      if (waitingSectionCount === 1) {
        onStatusChange?.(status);
      }
    } else {
      waitingSectionCount = Math.max(0, waitingSectionCount - 1);
      if (waitingSectionCount === 0) {
        onStatusChange?.(status);
      }
    }
  };

  if (parentSignal?.aborted) {
    batchController.abort();
  } else {
    parentSignal?.addEventListener('abort', abortBatch, { once: true });
  }

  const signal = batchController.signal;
  const sectionPromises = definitions.map(async (definition) => {
    const existing = existingPrd?.sections.find(section => section.id === definition.id);
    if (existingPrd?.manualEditedAt[definition.id] && existing) {
      return existing;
    }

    const content = await queuePrdWork(
      () => generateSectionWithRetry(
        client,
        context,
        definition.title,
        hints[definition.id] || '',
        signal,
        updateStatus
      ),
      signal
    );

    console.log(`[PRD][SECTION] ${definition.id}: ${content.slice(0, 80)}...`);
    return { id: definition.id, title: definition.title, content };
  });

  try {
    return await Promise.all(sectionPromises);
  } catch (error) {
    batchController.abort();
    await Promise.allSettled(sectionPromises);
    throw error;
  } finally {
    parentSignal?.removeEventListener('abort', abortBatch);
  }
}

export async function generateWorkflowPRD(
  aiClient: AiClientOrRouter,
  model: SemanticWorkflowModel,
  existingPRD?: WorkflowPRD,
  signal?: AbortSignal,
  onStatusChange?: (status: PRDGenerationStatus) => void
): Promise<WorkflowPRD> {
  const context = buildWorkflowContext(model);
  const sections = await generatePrdSections(
    aiClient,
    context,
    DEFAULT_WORKFLOW_SECTIONS,
    WORKFLOW_SECTION_HINTS,
    existingPRD,
    signal,
    onStatusChange
  );

  return {
    workflowId: model.workflowId,
    workflowName: model.name,
    sections,
    manualEditedAt: existingPRD?.manualEditedAt || {},
    version: (existingPRD?.version || 0) + 1,
    generatedAt: Date.now(),
    autoGenerated: true,
  };
}

export async function generateProjectPRD(
  aiClient: AiClientOrRouter,
  projectId: string,
  projectName: string,
  workflowModels: SemanticWorkflowModel[],
  existingPRD?: ProjectPRD,
  signal?: AbortSignal,
  onStatusChange?: (status: PRDGenerationStatus) => void
): Promise<ProjectPRD> {
  const context = buildProjectContext(projectName, workflowModels);
  const sections = await generatePrdSections(
    aiClient,
    context,
    DEFAULT_PROJECT_SECTIONS,
    PROJECT_SECTION_HINTS,
    existingPRD,
    signal,
    onStatusChange
  );

  return {
    projectId,
    projectName,
    sections,
    manualEditedAt: existingPRD?.manualEditedAt || {},
    version: (existingPRD?.version || 0) + 1,
    generatedAt: Date.now(),
    autoGenerated: true,
  };
}

export function createEmptyWorkflowPRD(workflowId: string, workflowName: string): WorkflowPRD {
  return {
    workflowId,
    workflowName,
    sections: DEFAULT_WORKFLOW_SECTIONS.map(s => ({
      id: s.id,
      title: s.title,
      content: ''
    })),
    manualEditedAt: {},
    version: 0,
    generatedAt: 0
  };
}

export function createEmptyProjectPRD(projectId: string, projectName: string): ProjectPRD {
  return {
    projectId,
    projectName,
    sections: DEFAULT_PROJECT_SECTIONS.map(s => ({
      id: s.id,
      title: s.title,
      content: ''
    })),
    manualEditedAt: {},
    version: 0,
    generatedAt: 0
  };
}

export async function generateSingleSection(
  aiClient: AiClientOrRouter,
  model: SemanticWorkflowModel,
  sectionId: string,
  existingPRD: WorkflowPRD,
  signal?: AbortSignal
): Promise<PRDSection | null> {
  const sectionMeta = DEFAULT_WORKFLOW_SECTIONS.find(s => s.id === sectionId);
  if (!sectionMeta) return null;

  const context = buildWorkflowContext(model);
  const existingSection = existingPRD.sections.find(s => s.id === sectionId);
  const previousContent = existingSection?.content
    ? `\nPrevious content for reference:\n${existingSection.content}\n`
    : '';

  const hint = WORKFLOW_SECTION_HINTS[sectionId] || '';
  const messages: AiMessage[] = [
    { role: 'system', content: SECTION_SYSTEM_PROMPT },
    { role: 'user', content: `${context}${previousContent}\n\nRewrite the "${sectionMeta.title}" section for this PRD.\n${hint}` },
  ];

  const text = await callAi(aiClient, messages, { temperature: 0.3, maxTokens: 800, signal });
  const content = normalizeGeneratedPrdSection(text, sectionMeta.title);

  if (!content) return null;

  return { id: sectionId, title: sectionMeta.title, content };
}

export async function elaborateSection(
  aiClient: AiClientOrRouter,
  model: SemanticWorkflowModel,
  sectionId: string,
  currentContent: string,
  signal?: AbortSignal
): Promise<string> {
  const sectionMeta = DEFAULT_WORKFLOW_SECTIONS.find(s => s.id === sectionId);
  const sectionTitle = sectionMeta?.title || sectionId;

  const context = buildWorkflowContext(model);

  const messages: AiMessage[] = [
    {
      role: 'system',
      content: 'You are a technical writer expanding a PRD section with more depth and detail. The surrounding UI already renders the section title, so begin directly with the content. Use headings only for distinct internal subtopics; never repeat the section title as a heading. Use plain markdown bullet points and prose. Do not wrap your entire response in code fences.',
    },
    {
      role: 'user',
      content: `${context}\n\nCurrent "${sectionTitle}" section:\n${currentContent}\n\nElaborate on this section with more depth, specific examples, edge cases, and technical detail relevant to this workflow. Expand the content significantly while staying focused on this section.`,
    },
  ];

  const text = await callAi(aiClient, messages, { temperature: 0.4, maxTokens: 1500, signal });
  return normalizeGeneratedPrdSection(text, sectionTitle);
}
