import type { AiClient, AiMessage } from './types';
import type { AiRouter } from './router';
import type { SemanticWorkflowModel } from '../lib/kiteframe/utils/extractSemanticWorkflowModel';

export interface PRDSection {
  id: string;
  title: string;
  content: string;
}

export interface WorkflowPRD {
  workflowId: string;
  workflowName: string;
  sections: PRDSection[];
  manualEditedAt: Record<string, number>;
  version: number;
  generatedAt: number;
  hash?: string;
  sectionHashes?: Record<string, string>;
  autoGenerated?: boolean;
  draft?: boolean;
}

export interface ProjectPRD {
  projectId: string;
  projectName: string;
  sections: PRDSection[];
  manualEditedAt: Record<string, number>;
  version: number;
  generatedAt: number;
  autoGenerated?: boolean;
}

type AiClientOrRouter = AiClient | AiRouter;

function isRouter(client: AiClientOrRouter): client is AiRouter {
  return 'chat' in client && !('stream' in client);
}

async function callAi(
  client: AiClientOrRouter,
  messages: AiMessage[],
  options: { temperature?: number; maxTokens?: number; signal?: AbortSignal }
): Promise<string> {
  if (isRouter(client)) {
    const response = await client.chat({
      taskType: 'prd_generation',
      messages,
      temperature: options.temperature,
      maxTokens: options.maxTokens,
      signal: options.signal,
    });
    return response.text;
  }
  const response = await client.chat({
    messages,
    temperature: options.temperature,
    maxTokens: options.maxTokens,
    signal: options.signal,
  });
  return response.text;
}

const DEFAULT_WORKFLOW_SECTIONS = [
  { id: 'overview', title: 'Overview' },
  { id: 'requirements', title: 'Requirements' },
  { id: 'user-flow', title: 'User Flow' },
  { id: 'inputs-outputs', title: 'Inputs & Outputs' },
  { id: 'failure-scenarios', title: 'Failure Scenarios' },
  { id: 'recovery-fallback', title: 'Recovery & Fallback Paths' },
  { id: 'operational-risks', title: 'Operational Risks' },
  { id: 'acceptance-criteria', title: 'Acceptance Criteria' },
];

const DEFAULT_PROJECT_SECTIONS = [
  { id: 'overview', title: 'Project Overview' },
  { id: 'goals', title: 'Goals & Objectives' },
  { id: 'architecture', title: 'System Architecture' },
  { id: 'workflows', title: 'Workflow Summary' },
  { id: 'assumptions', title: 'Assumptions' },
];

const WORKFLOW_SECTION_HINTS: Record<string, string> = {
  'overview': 'Cover: purpose of this workflow, who uses it, and what problem it solves. Use 3-5 bullet points.',
  'requirements': 'List the top functional and non-functional requirements. Max 5-6 bullet points.',
  'user-flow': 'Describe the step-by-step path from entry to exit. Use numbered steps. Include branching paths.',
  'inputs-outputs': 'List the key data inputs required and outputs produced. Use bullets or a short table.',
  'failure-scenarios': 'Identify the top 3-5 ways this workflow can fail: user errors, system errors, timeouts, edge cases.',
  'recovery-fallback': 'For each failure mode, describe the recovery or fallback path. Use bullet points.',
  'operational-risks': 'List 3-5 operational concerns: monitoring needs, SLA requirements, performance risks, dependencies.',
  'acceptance-criteria': 'Write 4-6 specific, testable acceptance criteria. Use checkboxes or Given/When/Then format.',
};

const PROJECT_SECTION_HINTS: Record<string, string> = {
  'overview': 'Summarize the project: what it does, who it serves, and what it delivers. 3-5 bullet points.',
  'goals': 'List the primary goals and measurable success metrics. Max 5 bullet points.',
  'architecture': 'Describe the system architecture and how the workflows connect. Keep it high-level.',
  'workflows': 'Briefly describe each workflow and its role in the overall system. One bullet per workflow.',
  'assumptions': 'List the key assumptions and constraints this project is built on. Max 5 bullet points.',
};

const SECTION_SYSTEM_PROMPT = 'You are a concise technical writer producing a single PRD section. Use bullet points and plain markdown. Aim for 80-150 words. Do not wrap your entire response in code fences. Do not repeat the section title as a heading.';

function buildWorkflowContext(model: SemanticWorkflowModel): string {
  const nodesDesc = model.nodes.map(n =>
    `- ${n.label || n.type} (${n.type})${n.description ? `: ${n.description}` : ''}`
  ).join('\n');

  const edgesDesc = model.edges.map(e => {
    const sourceNode = model.nodes.find(n => n.id === e.source);
    const targetNode = model.nodes.find(n => n.id === e.target);
    return `- ${sourceNode?.label || 'Node'} → ${targetNode?.label || 'Node'}${e.label ? ` (${e.label})` : ''}`;
  }).join('\n');

  return `Workflow: ${model.name}
Nodes (${model.nodeCount}):
${nodesDesc}

Connections:
${edgesDesc}

Entry: ${model.entryPoints.join(', ') || 'None identified'}
Exit: ${model.exitPoints.join(', ') || 'None identified'}
Primary Actions: ${model.primaryActions.join(', ') || 'None identified'}
Error Paths: ${model.errorPaths.join(', ') || 'None identified'}`;
}

function buildProjectContext(projectName: string, workflowModels: SemanticWorkflowModel[]): string {
  const workflowSummaries = workflowModels.map(w =>
    `- ${w.name}: ${w.nodeCount} nodes, ${w.edges.length} connections. Entry: ${w.entryPoints[0] || 'N/A'}, Exit: ${w.exitPoints[0] || 'N/A'}`
  ).join('\n');

  return `Project: ${projectName}
Total Workflows: ${workflowModels.length}

Workflows:
${workflowSummaries}`;
}

async function generateSectionText(
  client: AiClientOrRouter,
  context: string,
  sectionTitle: string,
  hint: string,
  signal?: AbortSignal
): Promise<string> {
  const messages: AiMessage[] = [
    { role: 'system', content: SECTION_SYSTEM_PROMPT },
    { role: 'user', content: `${context}\n\nWrite the "${sectionTitle}" section for this PRD.\n${hint}` },
  ];

  const text = await callAi(client, messages, { temperature: 0.3, maxTokens: 500, signal });
  return text.trim();
}

export async function generateWorkflowPRD(
  aiClient: AiClientOrRouter,
  model: SemanticWorkflowModel,
  existingPRD?: WorkflowPRD,
  signal?: AbortSignal
): Promise<WorkflowPRD> {
  const context = buildWorkflowContext(model);

  const settled = await Promise.allSettled(
    DEFAULT_WORKFLOW_SECTIONS.map(async (s) => {
      if (existingPRD?.manualEditedAt[s.id]) {
        const existing = existingPRD.sections.find(es => es.id === s.id);
        if (existing) return existing;
      }

      const content = await generateSectionText(
        aiClient,
        context,
        s.title,
        WORKFLOW_SECTION_HINTS[s.id] || '',
        signal
      );

      console.log(`[PRD][SECTION] ${s.id}: ${content.slice(0, 80)}...`);

      return { id: s.id, title: s.title, content };
    })
  );

  const sections: PRDSection[] = DEFAULT_WORKFLOW_SECTIONS.map((s, i) => {
    const result = settled[i];
    if (result.status === 'fulfilled') return result.value;
    console.warn(`[PRD][SECTION] ${s.id} failed, leaving empty:`, result.reason);
    return { id: s.id, title: s.title, content: '' };
  });

  return {
    workflowId: model.workflowId,
    workflowName: model.name,
    sections,
    manualEditedAt: existingPRD?.manualEditedAt || {},
    version: (existingPRD?.version || 0) + 1,
    generatedAt: Date.now(),
    autoGenerated: true,
  };
}

export async function generateProjectPRD(
  aiClient: AiClientOrRouter,
  projectId: string,
  projectName: string,
  workflowModels: SemanticWorkflowModel[],
  existingPRD?: ProjectPRD,
  signal?: AbortSignal
): Promise<ProjectPRD> {
  const context = buildProjectContext(projectName, workflowModels);

  const settled = await Promise.allSettled(
    DEFAULT_PROJECT_SECTIONS.map(async (s) => {
      if (existingPRD?.manualEditedAt[s.id]) {
        const existing = existingPRD.sections.find(es => es.id === s.id);
        if (existing) return existing;
      }

      const content = await generateSectionText(
        aiClient,
        context,
        s.title,
        PROJECT_SECTION_HINTS[s.id] || '',
        signal
      );

      console.log(`[PRD][SECTION] ${s.id}: ${content.slice(0, 80)}...`);

      return { id: s.id, title: s.title, content };
    })
  );

  const sections: PRDSection[] = DEFAULT_PROJECT_SECTIONS.map((s, i) => {
    const result = settled[i];
    if (result.status === 'fulfilled') return result.value;
    console.warn(`[PRD][SECTION] ${s.id} failed, leaving empty:`, result.reason);
    return { id: s.id, title: s.title, content: '' };
  });

  return {
    projectId,
    projectName,
    sections,
    manualEditedAt: existingPRD?.manualEditedAt || {},
    version: (existingPRD?.version || 0) + 1,
    generatedAt: Date.now(),
    autoGenerated: true,
  };
}

export function createEmptyWorkflowPRD(workflowId: string, workflowName: string): WorkflowPRD {
  return {
    workflowId,
    workflowName,
    sections: DEFAULT_WORKFLOW_SECTIONS.map(s => ({
      id: s.id,
      title: s.title,
      content: ''
    })),
    manualEditedAt: {},
    version: 0,
    generatedAt: 0
  };
}

export function createEmptyProjectPRD(projectId: string, projectName: string): ProjectPRD {
  return {
    projectId,
    projectName,
    sections: DEFAULT_PROJECT_SECTIONS.map(s => ({
      id: s.id,
      title: s.title,
      content: ''
    })),
    manualEditedAt: {},
    version: 0,
    generatedAt: 0
  };
}

export async function generateSingleSection(
  aiClient: AiClientOrRouter,
  model: SemanticWorkflowModel,
  sectionId: string,
  existingPRD: WorkflowPRD,
  signal?: AbortSignal
): Promise<PRDSection | null> {
  const sectionMeta = DEFAULT_WORKFLOW_SECTIONS.find(s => s.id === sectionId);
  if (!sectionMeta) return null;

  const context = buildWorkflowContext(model);
  const existingSection = existingPRD.sections.find(s => s.id === sectionId);
  const previousContent = existingSection?.content
    ? `\nPrevious content for reference:\n${existingSection.content}\n`
    : '';

  const hint = WORKFLOW_SECTION_HINTS[sectionId] || '';
  const messages: AiMessage[] = [
    { role: 'system', content: SECTION_SYSTEM_PROMPT },
    { role: 'user', content: `${context}${previousContent}\n\nRewrite the "${sectionMeta.title}" section for this PRD.\n${hint}` },
  ];

  const text = await callAi(aiClient, messages, { temperature: 0.3, maxTokens: 800, signal });
  const content = text.trim();

  if (!content) return null;

  return { id: sectionId, title: sectionMeta.title, content };
}

export async function elaborateSection(
  aiClient: AiClientOrRouter,
  model: SemanticWorkflowModel,
  sectionId: string,
  currentContent: string,
  signal?: AbortSignal
): Promise<string> {
  const sectionMeta = DEFAULT_WORKFLOW_SECTIONS.find(s => s.id === sectionId);
  const sectionTitle = sectionMeta?.title || sectionId;

  const context = buildWorkflowContext(model);

  const messages: AiMessage[] = [
    {
      role: 'system',
      content: 'You are a technical writer expanding a PRD section with more depth and detail. Use plain markdown bullet points and prose. Do not wrap your entire response in code fences. Do not repeat the section title as a heading.',
    },
    {
      role: 'user',
      content: `${context}\n\nCurrent "${sectionTitle}" section:\n${currentContent}\n\nElaborate on this section with more depth, specific examples, edge cases, and technical detail relevant to this workflow. Expand the content significantly while staying focused on this section.`,
    },
  ];

  const text = await callAi(aiClient, messages, { temperature: 0.4, maxTokens: 1500, signal });
  return text.trim();
}
