import type { AiClient, AiMessage } from './types';
import type { AiRouter } from './router';
import type { SemanticWorkflowModel } from '../lib/kiteframe/utils/extractSemanticWorkflowModel';

export interface PRDSection {
  id: string;
  title: string;
  content: string;
}

export interface WorkflowPRD {
  workflowId: string;
  workflowName: string;
  sections: PRDSection[];
  manualEditedAt: Record<string, number>;
  version: number;
  generatedAt: number;
  hash?: string;
  sectionHashes?: Record<string, string>;
  autoGenerated?: boolean;
  draft?: boolean;
}

export interface ProjectPRD {
  projectId: string;
  projectName: string;
  sections: PRDSection[];
  manualEditedAt: Record<string, number>;
  version: number;
  generatedAt: number;
  autoGenerated?: boolean;
}

type AiClientOrRouter = AiClient | AiRouter;

function isRouter(client: AiClientOrRouter): client is AiRouter {
  return 'chat' in client && !('stream' in client);
}

async function callAi(
  client: AiClientOrRouter,
  messages: AiMessage[],
  options: { temperature?: number; maxTokens?: number }
): Promise<string> {
  if (isRouter(client)) {
    const response = await client.chat({
      taskType: 'prd_generation',
      messages,
      temperature: options.temperature,
      maxTokens: options.maxTokens,
    });
    return response.text;
  }
  const response = await client.chat({
    messages,
    temperature: options.temperature,
    maxTokens: options.maxTokens,
  });
  return response.text;
}

const DEFAULT_WORKFLOW_SECTIONS = [
  { id: 'overview', title: 'Overview' },
  { id: 'requirements', title: 'Requirements' },
  { id: 'user-flow', title: 'User Flow' },
  { id: 'inputs-outputs', title: 'Inputs & Outputs' },
  { id: 'failure-scenarios', title: 'Failure Scenarios' },
  { id: 'recovery-fallback', title: 'Recovery & Fallback Paths' },
  { id: 'operational-risks', title: 'Operational Risks' },
  { id: 'acceptance-criteria', title: 'Acceptance Criteria' },
];

const DEFAULT_PROJECT_SECTIONS = [
  { id: 'overview', title: 'Project Overview' },
  { id: 'goals', title: 'Goals & Objectives' },
  { id: 'architecture', title: 'System Architecture' },
  { id: 'workflows', title: 'Workflow Summary' },
  { id: 'assumptions', title: 'Assumptions' },
];

function buildWorkflowPrompt(model: SemanticWorkflowModel): string {
  const nodesDesc = model.nodes.map(n => 
    `- ${n.label || n.type} (${n.type})${n.description ? `: ${n.description}` : ''}`
  ).join('\n');
  
  const edgesDesc = model.edges.map(e => {
    const sourceNode = model.nodes.find(n => n.id === e.source);
    const targetNode = model.nodes.find(n => n.id === e.target);
    return `- ${sourceNode?.label || 'Node'} → ${targetNode?.label || 'Node'}${e.label ? ` (${e.label})` : ''}`;
  }).join('\n');
  
  return `
Generate a Product Requirements Document (PRD) for this workflow:

Workflow Name: ${model.name}
Node Count: ${model.nodeCount}

Nodes:
${nodesDesc}

Connections:
${edgesDesc}

Entry Points: ${model.entryPoints.join(', ') || 'None identified'}
Exit Points: ${model.exitPoints.join(', ') || 'None identified'}
Forms: ${model.forms.length > 0 ? model.forms.map(f => f.nodeName).join(', ') : 'None'}
Screens: ${model.screens.length > 0 ? model.screens.map(s => s.name).join(', ') : 'None'}
Primary Actions: ${model.primaryActions.join(', ') || 'None identified'}
Error Paths: ${model.errorPaths.join(', ') || 'None identified'}

IMPORTANT: Reason about failure modes BEFORE happy paths. Every workflow can fail - identify how.

Return ONLY valid JSON in this exact format:
{
  "overview": "markdown content",
  "requirements": "markdown content", 
  "user-flow": "markdown content",
  "inputs-outputs": "markdown content",
  "failure-scenarios": "markdown content describing what can go wrong, edge cases, and error states",
  "recovery-fallback": "markdown content describing how the system recovers from failures, retry logic, fallback paths",
  "operational-risks": "markdown content about runtime risks, monitoring needs, and operational concerns",
  "acceptance-criteria": "markdown content"
}
`;
}

function buildProjectPrompt(
  projectName: string,
  workflowModels: SemanticWorkflowModel[]
): string {
  const workflowSummaries = workflowModels.map(w => 
    `- ${w.name}: ${w.nodeCount} nodes, ${w.edges.length} connections. Entry: ${w.entryPoints[0] || 'N/A'}, Exit: ${w.exitPoints[0] || 'N/A'}`
  ).join('\n');
  
  return `
Generate a Project-level PRD for:

Project Name: ${projectName}
Total Workflows: ${workflowModels.length}

Workflows:
${workflowSummaries}

Return ONLY valid JSON in this exact format:
{
  "overview": "markdown content",
  "goals": "markdown content",
  "architecture": "markdown content",
  "workflows": "markdown content",
  "assumptions": "markdown content"
}
`;
}

function sanitizeJSONString(str: string): string {
  let result = '';
  let inString = false;
  let i = 0;
  while (i < str.length) {
    const char = str[i];
    if (inString) {
      if (char === '\\') {
        result += char;
        i++;
        if (i < str.length) {
          result += str[i];
          i++;
        }
        continue;
      }
      if (char === '"') {
        inString = false;
        result += char;
        i++;
        continue;
      }
      if (char === '\n') {
        result += '\\n';
        i++;
        continue;
      }
      if (char === '\r') {
        result += '\\r';
        i++;
        continue;
      }
      if (char === '\t') {
        result += '\\t';
        i++;
        continue;
      }
    } else {
      if (char === '"') {
        inString = true;
      }
    }
    result += char;
    i++;
  }
  return result;
}

function parseAIResponse(text: string, sectionIds: string[]): Record<string, string> {
  let cleanedResponse = text
    .replace(/^```json\s?|```$/g, '')
    .replace(/^[^{]*/, '')
    .trim();
  
  const lastBraceIndex = cleanedResponse.lastIndexOf('}');
  if (lastBraceIndex !== -1) {
    cleanedResponse = cleanedResponse.substring(0, lastBraceIndex + 1);
  }

  cleanedResponse = sanitizeJSONString(cleanedResponse);
  
  try {
    const parsed = JSON.parse(cleanedResponse);
    const result: Record<string, string> = {};
    
    sectionIds.forEach(id => {
      result[id] = parsed[id] || '';
    });
    
    console.log('[PRD] parseAIResponse: sections extracted:', Object.fromEntries(
      Object.entries(result).map(([k, v]) => [k, v ? `${v.slice(0, 60)}...` : '(empty)'])
    ));
    return result;
  } catch (e) {
    console.error('[PRD] parseAIResponse failed to parse JSON:', e, '\nCleaned response (first 500 chars):', cleanedResponse?.slice(0, 500));
    return sectionIds.reduce((acc, id) => {
      acc[id] = '';
      return acc;
    }, {} as Record<string, string>);
  }
}

export async function generateWorkflowPRD(
  aiClient: AiClientOrRouter,
  model: SemanticWorkflowModel,
  existingPRD?: WorkflowPRD
): Promise<WorkflowPRD> {
  const prompt = buildWorkflowPrompt(model);
  
  const messages: AiMessage[] = [
    { role: 'system', content: 'You are a technical writer creating PRDs for workflow diagrams. Be concise and specific. Output only valid JSON. All newlines within JSON string values must be escaped as \\n — never include literal line breaks inside string values.' },
    { role: 'user', content: prompt }
  ];
  
  const responseText = await callAi(aiClient, messages, {
    temperature: 0.3,
    maxTokens: 4000,
  });
  
  const sectionIds = DEFAULT_WORKFLOW_SECTIONS.map(s => s.id);
  const parsedSections = parseAIResponse(responseText, sectionIds);
  
  const sections: PRDSection[] = DEFAULT_WORKFLOW_SECTIONS.map(s => {
    if (existingPRD?.manualEditedAt[s.id]) {
      const existingSection = existingPRD.sections.find(es => es.id === s.id);
      if (existingSection) {
        return existingSection;
      }
    }
    
    return {
      id: s.id,
      title: s.title,
      content: parsedSections[s.id] || ''
    };
  });
  
  return {
    workflowId: model.workflowId,
    workflowName: model.name,
    sections,
    manualEditedAt: existingPRD?.manualEditedAt || {},
    version: (existingPRD?.version || 0) + 1,
    generatedAt: Date.now(),
    autoGenerated: true
  };
}

export async function generateProjectPRD(
  aiClient: AiClientOrRouter,
  projectId: string,
  projectName: string,
  workflowModels: SemanticWorkflowModel[],
  existingPRD?: ProjectPRD
): Promise<ProjectPRD> {
  const prompt = buildProjectPrompt(projectName, workflowModels);
  
  const messages: AiMessage[] = [
    { role: 'system', content: 'You are a technical writer creating project PRDs. Be concise. Output only valid JSON. All newlines within JSON string values must be escaped as \\n — never include literal line breaks inside string values.' },
    { role: 'user', content: prompt }
  ];
  
  const responseText = await callAi(aiClient, messages, {
    temperature: 0.3,
    maxTokens: 3000,
  });
  
  const sectionIds = DEFAULT_PROJECT_SECTIONS.map(s => s.id);
  const parsedSections = parseAIResponse(responseText, sectionIds);
  
  const sections: PRDSection[] = DEFAULT_PROJECT_SECTIONS.map(s => {
    if (existingPRD?.manualEditedAt[s.id]) {
      const existingSection = existingPRD.sections.find(es => es.id === s.id);
      if (existingSection) {
        return existingSection;
      }
    }
    
    return {
      id: s.id,
      title: s.title,
      content: parsedSections[s.id] || ''
    };
  });
  
  return {
    projectId,
    projectName,
    sections,
    manualEditedAt: existingPRD?.manualEditedAt || {},
    version: (existingPRD?.version || 0) + 1,
    generatedAt: Date.now(),
    autoGenerated: true
  };
}

export function createEmptyWorkflowPRD(workflowId: string, workflowName: string): WorkflowPRD {
  return {
    workflowId,
    workflowName,
    sections: DEFAULT_WORKFLOW_SECTIONS.map(s => ({
      id: s.id,
      title: s.title,
      content: ''
    })),
    manualEditedAt: {},
    version: 0,
    generatedAt: 0
  };
}

export function createEmptyProjectPRD(projectId: string, projectName: string): ProjectPRD {
  return {
    projectId,
    projectName,
    sections: DEFAULT_PROJECT_SECTIONS.map(s => ({
      id: s.id,
      title: s.title,
      content: ''
    })),
    manualEditedAt: {},
    version: 0,
    generatedAt: 0
  };
}

export async function generateSingleSection(
  aiClient: AiClientOrRouter,
  model: SemanticWorkflowModel,
  sectionId: string,
  existingPRD: WorkflowPRD
): Promise<PRDSection | null> {
  const sectionMeta = DEFAULT_WORKFLOW_SECTIONS.find(s => s.id === sectionId);
  if (!sectionMeta) return null;
  
  const nodesDesc = model.nodes.map(n => 
    `- ${n.label || n.type} (${n.type})${n.description ? `: ${n.description}` : ''}`
  ).join('\n');
  
  const edgesDesc = model.edges.map(e => {
    const sourceNode = model.nodes.find(n => n.id === e.source);
    const targetNode = model.nodes.find(n => n.id === e.target);
    return `- ${sourceNode?.label || 'Node'} → ${targetNode?.label || 'Node'}${e.label ? ` (${e.label})` : ''}`;
  }).join('\n');
  
  const existingSection = existingPRD.sections.find(s => s.id === sectionId);
  
  const prompt = `
Regenerate ONLY the "${sectionMeta.title}" section for this workflow PRD:

Workflow: ${model.name}
Nodes:
${nodesDesc}

Connections:
${edgesDesc}

Entry Points: ${model.entryPoints.join(', ') || 'None identified'}
Exit Points: ${model.exitPoints.join(', ') || 'None identified'}
Primary Actions: ${model.primaryActions.join(', ') || 'None identified'}
Error Paths: ${model.errorPaths.join(', ') || 'None identified'}

${existingSection?.content ? `Previous content for reference:\n${existingSection.content}\n\n` : ''}
Return ONLY valid JSON in this format:
{"${sectionId}": "markdown content for ${sectionMeta.title}"}
`;

  const messages: AiMessage[] = [
    { role: 'system', content: 'You are a technical writer updating a specific PRD section. Be concise and specific. Output only valid JSON.' },
    { role: 'user', content: prompt }
  ];
  
  const responseText = await callAi(aiClient, messages, {
    temperature: 0.3,
    maxTokens: 800,
  });
  
  const parsedSections = parseAIResponse(responseText, [sectionId]);
  const content = parsedSections[sectionId];
  
  if (!content) return null;
  
  return {
    id: sectionId,
    title: sectionMeta.title,
    content
  };
}
