/**
 * Shared types for the document surfaces.
 *
 * The same document renders in two places at two very different sizes: the
 * right rail (a ~400-600px column shared with four other tabs) and the reader
 * pane (a dedicated, resizable column whose whole job is reading). Rather than
 * fork the renderer, every doc component takes a `density` and sizes itself
 * from it — one component, one set of behaviours, two typographic scales.
 */

export type DocDensity = 'rail' | 'reader';

export type ConfidenceLevel = 'high' | 'medium' | 'low';

/**
 * What a document tells its container about itself.
 *
 * The reader renders its own header and contents nav, but the document's title,
 * timestamp and section list are owned by whichever section component actually
 * loaded it. Rather than duplicate that loading (and its server/cache
 * reconciliation) in the reader, the section reports upward through
 * `onDocMeta` and the reader renders the chrome.
 */
export interface ReaderDocMeta {
  title: string;
  /** ISO timestamp of the newest known save, or null when nothing is stored. */
  updatedAt: string | null;
  version?: number;
  autoGenerated?: boolean;
  confidence?: ConfidenceLevel;
  sections: { id: string; title: string }[];
}

/**
 * DOM id for a section heading, namespaced by density.
 *
 * The rail and the reader can render the same document at the same time, so a
 * single `prd-section-<key>` id would appear twice in the document and
 * `getElementById` would resolve to whichever mounted first — scroll-spy and
 * jump-to-section in the reader would silently drive the rail instead.
 */
export function docSectionDomId(sectionKey: string, density: DocDensity = 'rail'): string {
  return density === 'reader' ? `reader-section-${sectionKey}` : `prd-section-${sectionKey}`;
}

/** Coarse confidence for a whole document, from how much content it carries. */
export function overallConfidence(sections: { content?: string }[]): ConfidenceLevel | undefined {
  if (sections.length === 0) return undefined;
  const total = sections.reduce((sum, s) => sum + (s.content?.length || 0), 0);
  const average = total / sections.length;
  if (average > 200) return 'high';
  if (average > 50) return 'medium';
  return 'low';
}
