/**
 * Export/Import utilities with versioning and validation
 * Provides reliable workflow serialization for enterprise use
 */

import { z } from 'zod';
import { Node, Edge, CanvasObject } from '../types';
import { validateColor, sanitizeText } from './validation';
import { 
  loadProjectPRD, 
  loadWorkflowPRD, 
  saveProjectPRD, 
  saveWorkflowPRD,
  listWorkflowPRDs 
} from './prdStorage';
import type { ProjectPRD, WorkflowPRD, PRDSection } from '../../../ai/prdEngine';
import { workflowIntentStore, type WorkflowIntent } from '../../../stores/workflowIntentStore';

// Export format version - bumped to 2.1.0 for PRD support
export const CURRENT_VERSION = '2.1.0';

// Version compatibility map
const VERSION_COMPATIBILITY: Record<string, string[]> = {
  '2.1.0': ['2.1.0', '2.0.0', '1.9.0', '1.8.0'],
  '2.0.0': ['2.0.0', '1.9.0', '1.8.0'],
  '1.9.0': ['1.9.0', '1.8.0', '1.7.0'],
  '1.8.0': ['1.8.0', '1.7.0']
};

// Schema for node data
const NodeDataSchema = z.object({
  label: z.string().optional(),
  description: z.string().optional(),
  icon: z.string().optional(),
  iconColor: z.string().optional(),
  displayText: z.string().optional(),
  src: z.string().optional(),
  filename: z.string().optional(),
  sourceType: z.enum(['upload', 'url', 'ai']).optional(),
  isImageBroken: z.boolean().optional(),
  // Webview node fields
  url: z.string().optional(),
  title: z.string().optional(),
  favicon: z.string().optional(),
  serviceName: z.string().optional(),
  serviceIcon: z.string().optional(),
  isLoading: z.boolean().optional(),
  loadError: z.string().optional(),
  showControls: z.boolean().optional(),
  colors: z.object({
    headerBackground: z.string().optional(),
    bodyBackground: z.string().optional(),
    borderColor: z.string().optional(),
    headerTextColor: z.string().optional(),
    bodyTextColor: z.string().optional()
  }).optional(),
  metadata: z.record(z.any()).optional()
});

// Schema for node
const NodeSchema = z.object({
  id: z.string(),
  type: z.string(),
  position: z.object({
    x: z.number(),
    y: z.number()
  }),
  data: NodeDataSchema,
  width: z.number().optional(),
  height: z.number().optional(),
  selected: z.boolean().optional(),
  draggable: z.boolean().optional(),
  selectable: z.boolean().optional(),
  resizable: z.boolean().optional(),
  zIndex: z.number().optional(),
  style: z.record(z.any()).optional(),
  hidden: z.boolean().optional()
});

// Schema for edge
const EdgeSchema = z.object({
  id: z.string(),
  source: z.string(),
  target: z.string(),
  sourceHandle: z.string().optional(),
  targetHandle: z.string().optional(),
  type: z.string().optional(),
  label: z.string().optional(),
  data: z.record(z.any()).optional(),
  style: z.record(z.any()).optional(),
  animated: z.boolean().optional(),
  selected: z.boolean().optional(),
  hidden: z.boolean().optional()
});

// Schema for canvas object
const CanvasObjectSchema = z.object({
  id: z.string(),
  type: z.enum(['text', 'shape', 'sticky', 'group']),
  position: z.object({
    x: z.number(),
    y: z.number()
  }),
  data: z.record(z.any()),
  width: z.number().optional(),
  height: z.number().optional(),
  rotation: z.number().optional(),
  style: z.record(z.any()).optional(),
  selected: z.boolean().optional(),
  locked: z.boolean().optional(),
  hidden: z.boolean().optional()
});

// Schema for viewport
const ViewportSchema = z.object({
  x: z.number(),
  y: z.number(),
  zoom: z.number()
});

// Schema for workflow metadata
const WorkflowMetadataSchema = z.object({
  name: z.string(),
  description: z.string().optional(),
  author: z.string().optional(),
  createdAt: z.string().optional(),
  modifiedAt: z.string().optional(),
  tags: z.array(z.string()).optional(),
  thumbnail: z.string().optional(),
  permissions: z.object({
    canEdit: z.boolean().optional(),
    canShare: z.boolean().optional(),
    canExport: z.boolean().optional()
  }).optional()
});

// Schema for PRD section
const PRDSectionSchema = z.object({
  id: z.string(),
  title: z.string(),
  content: z.string()
});

// Schema for workflow PRD
const WorkflowPRDSchema = z.object({
  workflowId: z.string(),
  workflowName: z.string(),
  sections: z.array(PRDSectionSchema),
  manualEditedAt: z.record(z.number()),
  version: z.number(),
  generatedAt: z.number(),
  hash: z.string().optional(),
  sectionHashes: z.record(z.string()).optional(),
  autoGenerated: z.boolean().optional(),
  draft: z.boolean().optional()
});

// Schema for project PRD
const ProjectPRDSchema = z.object({
  projectId: z.string(),
  projectName: z.string(),
  sections: z.array(PRDSectionSchema),
  manualEditedAt: z.record(z.number()),
  version: z.number(),
  generatedAt: z.number(),
  autoGenerated: z.boolean().optional()
});

// Schema for workflow intent
const WorkflowIntentSchema = z.object({
  primaryGoal: z.string(),
  userType: z.string(),
  successSignal: z.string(),
  failureModes: z.array(z.string()),
  maturity: z.enum(['draft', 'reviewed', 'stable']),
  confirmed: z.boolean()
});

// Schema for project overview details (Project Overview tab)
const ProjectOverviewSchema = z.object({
  name: z.string().optional(),
  description: z.string().optional(),
  categories: z.array(z.string()).optional(),
  createdAt: z.number().optional(),
  updatedAt: z.number().optional()
});

// Schema for project documentation data
const ProjectDocumentationSchema = z.object({
  projectPRD: ProjectPRDSchema.optional(),
  workflowPRDs: z.array(WorkflowPRDSchema).optional(),
  workflowIntents: z.record(WorkflowIntentSchema).optional(),
  workflowNames: z.record(z.string()).optional(),
  projectDescription: z.string().optional(),
  projectOverview: ProjectOverviewSchema.optional()
});

// Main export schema
const ExportSchema = z.object({
  version: z.string(),
  format: z.literal('kiteframe-workflow'),
  exportedAt: z.string(),
  metadata: WorkflowMetadataSchema,
  workflow: z.object({
    nodes: z.array(NodeSchema),
    edges: z.array(EdgeSchema),
    canvasObjects: z.array(CanvasObjectSchema).optional(),
    viewport: ViewportSchema.optional()
  }),
  documentation: ProjectDocumentationSchema.optional(),
  plugins: z.array(z.object({
    id: z.string(),
    version: z.string(),
    config: z.record(z.any()).optional()
  })).optional(),
  checksum: z.string().optional()
});

// Export type
export type WorkflowExport = z.infer<typeof ExportSchema>;

/**
 * Calculate checksum for data integrity
 */
function calculateChecksum(data: any): string {
  const str = JSON.stringify(data);
  let hash = 0;
  for (let i = 0; i < str.length; i++) {
    const char = str.charCodeAt(i);
    hash = ((hash << 5) - hash) + char;
    hash = hash & hash; // Convert to 32-bit integer
  }
  return Math.abs(hash).toString(36);
}

/**
 * Sanitize and validate workflow data before export
 * Filters out speculative/preview nodes and edges (experiment branches that haven't been accepted)
 */
function sanitizeWorkflowData(data: {
  nodes: Node[];
  edges: Edge[];
  canvasObjects?: CanvasObject[];
  viewport?: { x: number; y: number; zoom: number };
}): typeof data {
  // Filter out speculative nodes (experiment branches) and experiment node containers
  const committedNodes = data.nodes.filter(node => {
    if (node.type === 'experiment') return false;
    if (node.meta?.speculative === true) return false;
    if (node.data?.ui?.preview === true) return false;
    return true;
  });
  
  const committedNodeIds = new Set(committedNodes.map(n => n.id));
  
  // Filter out speculative edges and edges connected to filtered nodes
  const committedEdges = data.edges.filter(edge => {
    if (edge.meta?.speculative === true) return false;
    return committedNodeIds.has(edge.source) && committedNodeIds.has(edge.target);
  });
  
  // Sanitize nodes
  const sanitizedNodes = committedNodes.map(node => ({
    ...node,
    data: {
      ...node.data,
      label: sanitizeText(node.data.label || ''),
      description: sanitizeText(node.data.description || ''),
      displayText: sanitizeText(node.data.displayText || ''),
      colors: node.data.colors ? {
        ...node.data.colors,
        headerBackground: validateColor(node.data.colors.headerBackground || '') 
          ? node.data.colors.headerBackground : undefined,
        bodyBackground: validateColor(node.data.colors.bodyBackground || '') 
          ? node.data.colors.bodyBackground : undefined,
        borderColor: validateColor(node.data.colors.borderColor || '') 
          ? node.data.colors.borderColor : undefined,
        headerTextColor: validateColor(node.data.colors.headerTextColor || '') 
          ? node.data.colors.headerTextColor : undefined,
        bodyTextColor: validateColor(node.data.colors.bodyTextColor || '') 
          ? node.data.colors.bodyTextColor : undefined
      } : undefined
    }
  }));

  // Sanitize edges (using committedEdges which already filters speculative)
  const sanitizedEdges = committedEdges.map(edge => ({
    ...edge,
    label: edge.label ? sanitizeText(edge.label) : undefined
  }));

  // Sanitize canvas objects
  const sanitizedCanvasObjects = data.canvasObjects?.map(obj => ({
    ...obj,
    data: {
      ...obj.data,
      text: obj.data.text ? sanitizeText(obj.data.text) : undefined
    }
  }));

  return {
    nodes: sanitizedNodes,
    edges: sanitizedEdges,
    canvasObjects: sanitizedCanvasObjects,
    viewport: data.viewport
  };
}

/**
 * Export workflow to JSON format
 */
export function exportWorkflow(
  data: {
    nodes: Node[];
    edges: Edge[];
    canvasObjects?: CanvasObject[];
    viewport?: { x: number; y: number; zoom: number };
  },
  metadata: Partial<z.infer<typeof WorkflowMetadataSchema>> = {},
  options?: {
    projectId?: string;
    includeDocumentation?: boolean;
    workflowNames?: Record<string, string>;
    projectDescription?: string;
  }
): WorkflowExport {
  // Sanitize data
  const sanitizedData = sanitizeWorkflowData(data);

  // Collect documentation if requested
  let documentation: z.infer<typeof ProjectDocumentationSchema> | undefined;
  
  if (options?.includeDocumentation && options?.projectId) {
    const projectId = options.projectId;
    
    const projectPRD = loadProjectPRD(projectId);
    const workflowPRDIds = listWorkflowPRDs(projectId);
    const workflowPRDs: WorkflowPRD[] = [];
    
    for (const workflowId of workflowPRDIds) {
      const prd = loadWorkflowPRD(projectId, workflowId);
      if (prd) {
        workflowPRDs.push(prd);
      }
    }
    
    const allIntents = workflowIntentStore.getAll(projectId);
    const workflowIntents: Record<string, { primaryGoal: string; userType: string; successSignal: string; failureModes: string[]; maturity: 'draft' | 'reviewed' | 'stable'; confirmed: boolean }> = {};
    
    for (const [workflowId, intent] of Object.entries(allIntents)) {
      workflowIntents[workflowId] = {
        primaryGoal: intent.primaryGoal,
        userType: intent.userType,
        successSignal: intent.successSignal,
        failureModes: intent.failureModes,
        maturity: intent.maturity,
        confirmed: intent.confirmed
      };
    }
    
    let projectOverview: z.infer<typeof ProjectOverviewSchema> | undefined;
    try {
      const overviewRaw = typeof localStorage !== 'undefined'
        ? localStorage.getItem(`kiteframe-details-${projectId}`)
        : null;
      if (overviewRaw) {
        const parsed = JSON.parse(overviewRaw);
        projectOverview = {
          name: typeof parsed.name === 'string' ? parsed.name : undefined,
          description: typeof parsed.description === 'string' ? parsed.description : undefined,
          categories: Array.isArray(parsed.categories) ? parsed.categories.filter((c: unknown) => typeof c === 'string') : undefined,
          createdAt: typeof parsed.createdAt === 'number' ? parsed.createdAt : undefined,
          updatedAt: typeof parsed.updatedAt === 'number' ? parsed.updatedAt : undefined
        };
      }
    } catch (e) {
      console.warn('[exportWorkflow] Failed to read project overview:', e);
    }

    documentation = {
      projectPRD: projectPRD || undefined,
      workflowPRDs: workflowPRDs.length > 0 ? workflowPRDs : undefined,
      workflowIntents: Object.keys(workflowIntents).length > 0 ? workflowIntents : undefined,
      workflowNames: options.workflowNames,
      projectDescription: options.projectDescription,
      projectOverview
    };
  }

  // Create export object
  const exportData: WorkflowExport = {
    version: CURRENT_VERSION,
    format: 'kiteframe-workflow',
    exportedAt: new Date().toISOString(),
    metadata: {
      name: metadata.name || 'Untitled Workflow',
      description: metadata.description,
      author: metadata.author,
      createdAt: metadata.createdAt || new Date().toISOString(),
      modifiedAt: new Date().toISOString(),
      tags: metadata.tags,
      thumbnail: metadata.thumbnail,
      permissions: metadata.permissions
    },
    workflow: {
      nodes: sanitizedData.nodes as any[], // Type assertion needed due to complex nested types
      edges: sanitizedData.edges as any[],
      canvasObjects: sanitizedData.canvasObjects as any[],
      viewport: sanitizedData.viewport
    },
    documentation,
    plugins: [],
    checksum: ''
  };

  // Calculate checksum
  exportData.checksum = calculateChecksum(exportData.workflow);

  // Validate export data
  const validation = ExportSchema.safeParse(exportData);
  if (!validation.success) {
    console.error('Export validation failed:', validation.error);
    throw new Error('Failed to validate export data');
  }

  return exportData;
}

/**
 * Export workflow as downloadable file
 */
export function downloadWorkflow(
  exportData: WorkflowExport,
  filename?: string
): void {
  const jsonStr = JSON.stringify(exportData, null, 2);
  const blob = new Blob([jsonStr], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  
  const a = document.createElement('a');
  a.href = url;
  a.download = filename || `workflow-${Date.now()}.kiteframe`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  
  URL.revokeObjectURL(url);
}

// Workflow intent type for export/import
export interface ExportedWorkflowIntent {
  primaryGoal: string;
  userType: string;
  successSignal: string;
  failureModes: string[];
  maturity: 'draft' | 'reviewed' | 'stable';
  confirmed: boolean;
}

// Documentation import result type
export interface ImportedProjectOverview {
  name?: string;
  description?: string;
  categories?: string[];
  createdAt?: number;
  updatedAt?: number;
}

export interface ImportedDocumentation {
  projectPRD?: ProjectPRD;
  workflowPRDs?: WorkflowPRD[];
  workflowIntents?: Record<string, ExportedWorkflowIntent>;
  workflowNames?: Record<string, string>;
  projectDescription?: string;
  projectOverview?: ImportedProjectOverview;
}

/**
 * Import workflow from JSON
 */
export function importWorkflow(
  jsonData: string | WorkflowExport,
  options?: {
    restoreDocumentation?: boolean;
    projectId?: string;
    workflowIdMap?: Record<string, string>;
    currentWorkflowNames?: Record<string, string>;
  }
): {
  success: boolean;
  data?: {
    nodes: Node[];
    edges: Edge[];
    canvasObjects?: CanvasObject[];
    viewport?: { x: number; y: number; zoom: number };
    metadata: z.infer<typeof WorkflowMetadataSchema>;
    documentation?: ImportedDocumentation;
  };
  error?: string;
  warnings?: string[];
} {
  try {
    // Parse JSON if string
    const data = typeof jsonData === 'string' ? JSON.parse(jsonData) : jsonData;
    
    // Validate schema
    const validation = ExportSchema.safeParse(data);
    if (!validation.success) {
      return {
        success: false,
        error: 'Invalid workflow format',
        warnings: validation.error.errors.map(e => `${e.path.join('.')}: ${e.message}`)
      };
    }

    const validData = validation.data;
    
    // Check version compatibility
    const isCompatible = isVersionCompatible(validData.version, CURRENT_VERSION);
    const warnings: string[] = [];
    
    if (!isCompatible) {
      warnings.push(`Workflow version ${validData.version} may not be fully compatible with current version ${CURRENT_VERSION}`);
    }

    // Verify checksum
    if (validData.checksum) {
      const calculatedChecksum = calculateChecksum(validData.workflow);
      if (calculatedChecksum !== validData.checksum) {
        warnings.push('Workflow data integrity check failed - data may have been modified');
      }
    }

    // Migrate data if needed
    const migratedData = migrateWorkflowData(validData, CURRENT_VERSION);
    
    // Sanitize imported data
    const sanitizedData = sanitizeWorkflowData(migratedData.workflow);

    // Extract documentation if present
    let documentation: ImportedDocumentation | undefined;
    if (migratedData.documentation) {
      documentation = {
        projectPRD: migratedData.documentation.projectPRD as ProjectPRD | undefined,
        workflowPRDs: migratedData.documentation.workflowPRDs as WorkflowPRD[] | undefined,
        workflowIntents: migratedData.documentation.workflowIntents as Record<string, ExportedWorkflowIntent> | undefined,
        workflowNames: migratedData.documentation.workflowNames,
        projectDescription: migratedData.documentation.projectDescription,
        projectOverview: migratedData.documentation.projectOverview as ImportedProjectOverview | undefined
      };
      
      // Restore documentation to localStorage if requested
      if (options?.restoreDocumentation && options?.projectId) {
        const projectId = options.projectId;

        if (documentation.projectOverview) {
          const overviewKey = `kiteframe-details-${projectId}`;
          try {
            const existingRaw = typeof localStorage !== 'undefined'
              ? localStorage.getItem(overviewKey)
              : null;
            const existing = existingRaw ? JSON.parse(existingRaw) : {};
            const incoming = documentation.projectOverview;
            const merged = {
              ...existing,
              name: incoming.name ?? existing.name ?? '',
              description: incoming.description ?? existing.description ?? '',
              categories: incoming.categories ?? existing.categories ?? [],
              createdAt: existing.createdAt ?? incoming.createdAt ?? Date.now(),
              updatedAt: Date.now()
            };
            if (typeof localStorage !== 'undefined') {
              localStorage.setItem(overviewKey, JSON.stringify(merged));
            }
          } catch (e) {
            console.warn('[importWorkflow] Failed to restore project overview:', e);
          }
        }

        if (documentation.projectPRD) {
          const restoredProjectPRD: ProjectPRD = {
            ...documentation.projectPRD,
            projectId,
            projectName: documentation.projectPRD.projectName || migratedData.metadata.name
          };
          saveProjectPRD(projectId, restoredProjectPRD);
        }
        
        if (documentation.workflowPRDs) {
          // Build name-to-ID mapping from current project workflows for name-based matching
          const nameToCurrentId = new Map<string, string>();
          if (options?.currentWorkflowNames) {
            Object.entries(options.currentWorkflowNames).forEach(([id, name]) => {
              const normalizedName = name.toLowerCase().trim();
              nameToCurrentId.set(normalizedName, id);
            });
          }
          
          for (const workflowPRD of documentation.workflowPRDs) {
            const originalId = workflowPRD.workflowId;
            const originalName = documentation.workflowNames?.[originalId] || workflowPRD.workflowName;
            
            // Priority 1: Use explicit workflowIdMap if provided
            // Priority 2: Match by name to current project workflows
            // Priority 3: Fall back to original ID (imported workflow keeps its ID)
            let targetId = originalId;
            if (options?.workflowIdMap?.[originalId]) {
              targetId = options.workflowIdMap[originalId];
            } else if (nameToCurrentId.has(originalName.toLowerCase().trim())) {
              targetId = nameToCurrentId.get(originalName.toLowerCase().trim())!;
            }
            
            const restoredWorkflowPRD: WorkflowPRD = {
              ...workflowPRD,
              workflowId: targetId,
              workflowName: originalName
            };
            saveWorkflowPRD(projectId, targetId, restoredWorkflowPRD);
          }
        }
        
        if (documentation.workflowIntents) {
          const nameToCurrentId = new Map<string, string>();
          if (options?.currentWorkflowNames) {
            Object.entries(options.currentWorkflowNames).forEach(([id, name]) => {
              const normalizedName = name.toLowerCase().trim();
              nameToCurrentId.set(normalizedName, id);
            });
          }
          
          for (const [originalId, intent] of Object.entries(documentation.workflowIntents)) {
            const originalName = documentation.workflowNames?.[originalId] || '';
            
            let targetId = originalId;
            if (options?.workflowIdMap?.[originalId]) {
              targetId = options.workflowIdMap[originalId];
            } else if (originalName && nameToCurrentId.has(originalName.toLowerCase().trim())) {
              targetId = nameToCurrentId.get(originalName.toLowerCase().trim())!;
            }
            
            const restoredIntent: WorkflowIntent = {
              primaryGoal: intent.primaryGoal,
              userType: intent.userType,
              successSignal: intent.successSignal,
              failureModes: intent.failureModes,
              maturity: intent.maturity,
              confirmed: intent.confirmed,
              isStale: false
            };
            workflowIntentStore.set(projectId, targetId, restoredIntent);
          }
        }
      }
    }

    return {
      success: true,
      data: {
        ...sanitizedData,
        metadata: migratedData.metadata,
        documentation
      },
      warnings: warnings.length > 0 ? warnings : undefined
    };
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Failed to import workflow'
    };
  }
}

/**
 * Check version compatibility
 */
function isVersionCompatible(sourceVersion: string, targetVersion: string): boolean {
  const compatibleVersions = VERSION_COMPATIBILITY[targetVersion] || [targetVersion];
  return compatibleVersions.includes(sourceVersion);
}

/**
 * Migrate workflow data to current version
 */
function migrateWorkflowData(
  data: WorkflowExport,
  targetVersion: string
): WorkflowExport {
  // Version-specific migrations
  let migrated = { ...data };
  
  // Example migration from 1.x to 2.x
  if (data.version.startsWith('1.') && targetVersion.startsWith('2.')) {
    // Add any missing fields required in v2
    migrated.workflow.nodes = migrated.workflow.nodes.map(node => ({
      ...node,
      resizable: node.resizable ?? true,
      draggable: node.draggable ?? true,
      selectable: node.selectable ?? true
    }));
  }
  
  // Update version
  migrated.version = targetVersion;
  
  return migrated;
}

/**
 * Import workflow from file
 */
export async function importWorkflowFromFile(file: File): Promise<ReturnType<typeof importWorkflow>> {
  return new Promise((resolve) => {
    const reader = new FileReader();
    
    reader.onload = (e) => {
      try {
        const content = e.target?.result as string;
        const result = importWorkflow(content);
        resolve(result);
      } catch (error) {
        resolve({
          success: false,
          error: 'Failed to read file'
        });
      }
    };
    
    reader.onerror = () => {
      resolve({
        success: false,
        error: 'Failed to read file'
      });
    };
    
    reader.readAsText(file);
  });
}

/**
 * Validate workflow file
 */
export function validateWorkflowFile(file: File): {
  valid: boolean;
  error?: string;
} {
  // Check file type
  if (!file.name.endsWith('.kiteframe') && !file.name.endsWith('.json')) {
    return {
      valid: false,
      error: 'Invalid file type. Please select a .kiteframe or .json file'
    };
  }
  
  // Check file size (10MB max)
  if (file.size > 10485760) {
    return {
      valid: false,
      error: 'File too large. Maximum size is 10MB'
    };
  }
  
  return { valid: true };
}