// GENERATED by scripts/fetch-coffee-photos.mjs — do not edit by hand.
//
// Openly-licensed coffee imagery from Wikimedia Commons, used as stand-in
// photography for atlas entries until real photos are dropped in. Every entry
// keeps its author and licence so the UI can credit it. Files live in
// client/public/coffee/photos/.

export interface PooledPhoto {
  key: string;
  src: string;
  alt: string;
  credit: string;
  creditUrl: string;
  license: string;
}

export const PHOTO_POOL: PooledPhoto[] = [
  {
    key: "2019-11-08-coffee-barista-inside-cafe-main-church-street-cro",
    src: "/coffee/photos/2019-11-08-coffee-barista-inside-cafe-main-church-street-cro.jpg",
    alt: "Coffee barista inside Cafe Main, Church Street, Cromer",
    credit: "Kolforn",
    creditUrl: "https://commons.wikimedia.org/wiki/File:-2019-11-08_Coffee_barista_inside_Cafe_Main,_Church_Street,_Cromer.JPG",
    license: "CC BY-SA 4.0",
  },
  {
    key: "2019-11-08-inside-cafe-main-church-street-cromer",
    src: "/coffee/photos/2019-11-08-inside-cafe-main-church-street-cromer.jpg",
    alt: "Inside Cafe Main, Church Street, Cromer",
    credit: "Kolforn",
    creditUrl: "https://commons.wikimedia.org/wiki/File:-2019-11-08_Inside_Cafe_Main,_Church_Street,_Cromer.JPG",
    license: "CC BY-SA 4.0",
  },
  {
    key: "75-degrees-green-coffee",
    src: "/coffee/photos/75-degrees-green-coffee.jpg",
    alt: "75 degrees green coffee",
    credit: "Dan Bollinger",
    creditUrl: "https://commons.wikimedia.org/wiki/File:75_degrees_green_coffee.png",
    license: "CC BY-SA 3.0",
  },
  {
    key: "barista-prepares-espresso-at-coffee-shop",
    src: "/coffee/photos/barista-prepares-espresso-at-coffee-shop.jpg",
    alt: "Barista prepares espresso at coffee shop",
    credit: "Shixart1985",
    creditUrl: "https://commons.wikimedia.org/wiki/File:Barista_prepares_espresso_at_coffee_shop.jpg",
    license: "CC BY 2.0",
  },
  {
    key: "beans-dropping-from-a-coffee-roaster",
    src: "/coffee/photos/beans-dropping-from-a-coffee-roaster.jpg",
    alt: "Beans Dropping from a Coffee Roaster",
    credit: "Jkafader",
    creditUrl: "https://commons.wikimedia.org/wiki/File:Beans_Dropping_from_a_Coffee_Roaster.JPG",
    license: "CC BY-SA 3.0",
  },
  {
    key: "cappuccino-latte-art-2006-04-14",
    src: "/coffee/photos/cappuccino-latte-art-2006-04-14.jpg",
    alt: "Cappuccino latte art 2006 04 14",
    credit: "Lukas Kolbe",
    creditUrl: "https://commons.wikimedia.org/wiki/File:Cappuccino_latte_art_2006-04-14.jpg",
    license: "CC BY-SA 2.5",
  },
  {
    key: "cappuccino-with-latte-art-on-coffee-right-in-brno-brno-city-",
    src: "/coffee/photos/cappuccino-with-latte-art-on-coffee-right-in-brno-brno-city-.jpg",
    alt: "Cappuccino with latte art on Coffee Right in Brno, Brno City District",
    credit: "Frettie",
    creditUrl: "https://commons.wikimedia.org/wiki/File:Cappuccino_with_latte_art_on_Coffee_Right_in_Brno,_Brno-City_District.jpg",
    license: "CC BY 3.0",
  },
  {
    key: "coffee-roaster-1",
    src: "/coffee/photos/coffee-roaster-1.jpg",
    alt: "Coffee Roaster 1",
    credit: "Visitor7",
    creditUrl: "https://commons.wikimedia.org/wiki/File:Coffee_Roaster-1.jpg",
    license: "CC BY-SA 3.0",
  },
  {
    key: "cold-drip-coffee-2",
    src: "/coffee/photos/cold-drip-coffee-2.jpg",
    alt: "Cold drip coffee 2",
    credit: "Misaochan",
    creditUrl: "https://commons.wikimedia.org/wiki/File:Cold_drip_coffee_2.jpg",
    license: "CC BY 3.0",
  },
  {
    key: "dfc-4594-empty-seaside-terrace-at-dusk-shaded-by-triangular-",
    src: "/coffee/photos/dfc-4594-empty-seaside-terrace-at-dusk-shaded-by-triangular-.jpg",
    alt: "DFC 4594 Empty seaside terrace at dusk shaded by triangular sail canopies as the sun sets",
    credit: "PattayaPatrol",
    creditUrl: "https://commons.wikimedia.org/wiki/File:DFC_4594_Empty_seaside_terrace_at_dusk_shaded_by_triangular_sail_canopies_as_the_sun_sets.jpg",
    license: "CC BY-SA 4.0",
  },
  {
    key: "drip-coffee-bangkok",
    src: "/coffee/photos/drip-coffee-bangkok.jpg",
    alt: "Drip Coffee Bangkok",
    credit: "Takeaway",
    creditUrl: "https://commons.wikimedia.org/wiki/File:Drip_Coffee_Bangkok.jpg",
    license: "CC BY-SA 3.0",
  },
  {
    key: "dscf1086-a-quiet-covered-wooden-walkway-lined-with-cozy-seat",
    src: "/coffee/photos/dscf1086-a-quiet-covered-wooden-walkway-lined-with-cozy-seat.jpg",
    alt: "DSCF1086 A quiet covered wooden walkway lined with cozy seating and warm hanging lights opening onto a lush garden courtyard",
    credit: "PattayaPatrol",
    creditUrl: "https://commons.wikimedia.org/wiki/File:DSCF1086_A_quiet_covered_wooden_walkway_lined_with_cozy_seating_and_warm_hanging_lights_opening_onto_a_lush_garden_courtyard.jpg",
    license: "CC BY-SA 4.0",
  },
  {
    key: "figaro-coffee-shop-interior-in-salawag-dasmarin-as-cavite-19",
    src: "/coffee/photos/figaro-coffee-shop-interior-in-salawag-dasmarin-as-cavite-19.jpg",
    alt: "Figaro Coffee shop interior in Salawag, Dasmariñas, Cavite — 19 Mar 2022",
    credit: "UndueMarmot",
    creditUrl: "https://commons.wikimedia.org/wiki/File:Figaro_Coffee_shop_interior_in_Salawag,_Dasmari%C3%B1as,_Cavite_%E2%80%94_19_Mar_2022.jpg",
    license: "CC BY 4.0",
  },
  {
    key: "gustav-wentzel-ktakaffe-lkm-000334-lillehammer-kunstmuseum",
    src: "/coffee/photos/gustav-wentzel-ktakaffe-lkm-000334-lillehammer-kunstmuseum.jpg",
    alt: "Gustav Wentzel Øktakaffe LKM.000334 Lillehammer Kunstmuseum",
    credit: "Gustav Wentzel",
    creditUrl: "https://commons.wikimedia.org/wiki/File:Gustav_Wentzel_-_%C3%98ktakaffe_-_LKM.000334_-_Lillehammer_Kunstmuseum.jpg",
    license: "Public domain",
  },
  {
    key: "hot-coffee-on-a-rainy-day-flickr-deapeajay",
    src: "/coffee/photos/hot-coffee-on-a-rainy-day-flickr-deapeajay.jpg",
    alt: "Hot Coffee on a rainy day Flickr DeaPeaJay",
    credit: "David Joyce from Gray, TN, United States",
    creditUrl: "https://commons.wikimedia.org/wiki/File:Hot_Coffee_on_a_rainy_day_-_Flickr_-_DeaPeaJay.jpg",
    license: "CC BY-SA 2.0",
  },
  {
    key: "juan-gris-le-moulin-a-cafe-google-art-project",
    src: "/coffee/photos/juan-gris-le-moulin-a-cafe-google-art-project.jpg",
    alt: "Juan Gris Le moulin à café Google Art Project",
    credit: "Juan Gris",
    creditUrl: "https://commons.wikimedia.org/wiki/File:Juan_Gris_-_Le_moulin_%C3%A0_caf%C3%A9_-_Google_Art_Project.jpg",
    license: "Public domain",
  },
  {
    key: "making-of-latte-art-of-cappuccino-on-coffee-right-in-brno-br",
    src: "/coffee/photos/making-of-latte-art-of-cappuccino-on-coffee-right-in-brno-br.jpg",
    alt: "Making of Latte art of cappuccino on Coffee Right in Brno, Brno City District",
    credit: "Frettie",
    creditUrl: "https://commons.wikimedia.org/wiki/File:Making_of_Latte_art_of_cappuccino_on_Coffee_Right_in_Brno,_Brno-City_District.jpg",
    license: "CC BY 3.0",
  },
  {
    key: "mi-tierra-restaurant-san-antonio-now-serving-number-65",
    src: "/coffee/photos/mi-tierra-restaurant-san-antonio-now-serving-number-65.jpg",
    alt: "Mi Tierra Restaurant, San Antonio Now Serving Number 65",
    credit: "Mathieu Plourde",
    creditUrl: "https://commons.wikimedia.org/wiki/File:Mi_Tierra_Restaurant,_San_Antonio_Now_Serving_Number_65.jpg",
    license: "CC BY 2.0",
  },
  {
    key: "moulin-a-cafe-peugeot-face",
    src: "/coffee/photos/moulin-a-cafe-peugeot-face.jpg",
    alt: "Moulin à café Peugeot face",
    credit: "Clément Bucco-Lechat",
    creditUrl: "https://commons.wikimedia.org/wiki/File:Moulin_%C3%A0_caf%C3%A9_Peugeot_-_face.jpg",
    license: "CC BY-SA 3.0",
  },
  {
    key: "the-magnetic-counter-01-8034827583",
    src: "/coffee/photos/the-magnetic-counter-01-8034827583.jpg",
    alt: "The magnetic counter 01 (8034827583)",
    credit: "Bosc d'Anjou from New York, NY, USA",
    creditUrl: "https://commons.wikimedia.org/wiki/File:The_magnetic_counter_01_(8034827583).jpg",
    license: "CC BY 2.0",
  },
  {
    key: "the-st-john-s-coffee-shop-in-downtown-covington-louisiana-in",
    src: "/coffee/photos/the-st-john-s-coffee-shop-in-downtown-covington-louisiana-in.jpg",
    alt: "The St John's Coffee Shop in downtown Covington Louisiana, interior, August 2023",
    credit: "abbeyprivate",
    creditUrl: "https://commons.wikimedia.org/wiki/File:The_St_John%27s_Coffee_Shop_in_downtown_Covington_Louisiana,_interior,_August_2023.jpg",
    license: "Public domain",
  },
  {
    key: "unroasted-coffee",
    src: "/coffee/photos/unroasted-coffee.jpg",
    alt: "Unroasted coffee",
    credit: "Fernando Rebêlo",
    creditUrl: "https://commons.wikimedia.org/wiki/File:Unroasted_coffee.jpg",
    license: "CC BY-SA 3.0",
  },
  {
    key: "urban-bean-coffee-shop-uptown-minneapolis-17198299107",
    src: "/coffee/photos/urban-bean-coffee-shop-uptown-minneapolis-17198299107.jpg",
    alt: "Urban Bean Coffee Shop, Uptown Minneapolis (17198299107)",
    credit: "Tony Webster from Minneapolis, Minnesota, United States",
    creditUrl: "https://commons.wikimedia.org/wiki/File:Urban_Bean_Coffee_Shop,_Uptown_Minneapolis_(17198299107).jpg",
    license: "CC BY 2.0",
  },
];

const BY_KEY = new Map(PHOTO_POOL.map((photo) => [photo.key, photo]));

/**
 * Looks up a pooled photo and shapes it for the `Photo` content type. Throws
 * on an unknown key so a renamed image surfaces immediately rather than
 * rendering a broken tile.
 */
export function pooledPhoto(key: string, alt?: string) {
  const photo = BY_KEY.get(key);
  if (!photo) {
    throw new Error(
      `Unknown pooled photo "${key}". Run scripts/fetch-coffee-photos.mjs or pick a key from PHOTO_POOL.`,
    );
  }
  return {
    src: photo.src,
    alt: alt ?? photo.alt,
    credit: photo.credit,
    creditUrl: photo.creditUrl,
    license: photo.license,
    isPlaceholder: true,
  };
}
